config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "static_pages/home"
    get "static_pages/help"
    get "static_pages/contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    # resources :users, only: %i(new create)
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("app_name"), static_pages_home_path, id: "logo" %>
    <%= link_to t("english"), locale: :en %>
    <%= link_to t("vietnamese"), locale: :vi %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), static_pages_home_path %></li>
        <li><%= link_to t("help"), static_pages_help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users.session.user"), user_path(@current_user)%></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              <%= t "users.session.account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "users.session.profile", current_user %></li>
              <li><%= link_to "users.session.settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to "users.session.logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
        <li><%= link_to t("contact"), static_pages_contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= full_title yield :title %></title>
    <title><%= yield(:title) %> | <%= t "title_page" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>